import { HOUR_IN_MILLISECONDS, MINUTE_IN_MILLISECONDS } from "./utils/date";

export const RESERVATION_LENGTH_IN_MINUTES = 15;
export const RESERVATION_LENGTH =
  MINUTE_IN_MILLISECONDS * RESERVATION_LENGTH_IN_MINUTES; // 15 Min Slots
export const RESERVATION_CUTOFF = HOUR_IN_MILLISECONDS * 24; // 24 hours in advance.
export const MAX_SLOTS_PER_DAY = (60 / RESERVATION_LENGTH_IN_MINUTES) * 24;
