export const SECOND_IN_MILLISECONDS = 1000;
export const MINUTE_IN_MILLISECONDS = SECOND_IN_MILLISECONDS * 60;
export const HOUR_IN_MILLISECONDS = MINUTE_IN_MILLISECONDS * 60;

export const RESERVATION_LENGTH = MINUTE_IN_MILLISECONDS * 15; // 15 Min Slots
export const RESERVATION_CUTOFF = HOUR_IN_MILLISECONDS * 24; // 24 hours in advance.
